M48
; DRILL file {KiCad (6.0.5-0)} date 2022 July 05, Tuesday 17:16:16
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-05T17:16:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X2.2311Y-3.4449
X2.2311Y-3.563
X3.7293Y-3.4862
X3.7293Y-3.6594
T0
M30
